version: "3.8"
services:
  my_todo:
    build: ./my_todo
    volumes:
      - ./my_todo:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=todos
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
