version: "3.8"
services:
  my_todo:
    build: ./my_todo
    volumes:
      - ./my_todo:/app
      - ./my_todo/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=todos
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p$$MYSQL_ROOT_PASSWORD", "ping"]
      interval: 10s
      timeout: 20s
      retries: 10
    restart: always

volumes:
  mysql-data:
