version: '3.8'
services:
  db:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: somepassword
      MYSQL_PASSWORD: password

volumes:
  mysql_data:
